/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */
 

public void imgTogButton1_click1(GImageToggleButton source, GEvent event) { //_CODE_:imgTogButton1:786408:
  println("imgTogButton1 - GImageToggleButton event occured " + System.currentTimeMillis()%10000000 );

  
  if(sw1 == 0)
   {
     // led 1 on
     sw1 = 1;
     led_on(0);
   }
  else 
   {
     // led 1 off
     sw1 = 0;
     led_off(0);
   }
} //_CODE_:imgTogButton1:786408:

public void imgTogButton2_click1(GImageToggleButton source, GEvent event) { //_CODE_:imgTogButton2:970419:
  println("imgTogButton2 - GImageToggleButton event occured " + System.currentTimeMillis()%10000000 );


if(sw2 == 0)
   {
     // led 1 on
     sw2 = 1;
     led_on(1);
   }
  else 
   {
     // led 1 off
     sw2 = 0;
     led_off(1);
   }

} //_CODE_:imgTogButton2:970419:

public void imgTogButton3_click1(GImageToggleButton source, GEvent event) { //_CODE_:imgTogButton3:695034:
  println("imgTogButton3 - GImageToggleButton event occured " + System.currentTimeMillis()%10000000 );

if(sw3 == 0)
   {
     // led 1 on
     sw3 = 1;
     led_on(2);
   }
  else 
   {
     // led 1 off
     sw3 = 0;
     led_off(2);
   }


} //_CODE_:imgTogButton3:695034:

public void imgTogButton4_click1(GImageToggleButton source, GEvent event) { //_CODE_:imgTogButton4:246405:
  println("imgTogButton4 - GImageToggleButton event occured " + System.currentTimeMillis()%10000000 );

if(sw4 == 0)
   {
     // led 1 on
     sw4 = 1;
     led_on(3);
   }
  else 
   {
     // led 1 off
     sw4 = 0;
     led_off(3);
   }

} //_CODE_:imgTogButton4:246405:

public void imgTogButton5_click1(GImageToggleButton source, GEvent event) { //_CODE_:imgTogButton5:953391:
  println("imgTogButton5 - GImageToggleButton event occured " + System.currentTimeMillis()%10000000 );

if(sw5 == 0)
   {
     // led 1 on
     sw5 = 1;
     led_on(4);
   }
  else 
   {
     // led 1 off
     sw5 = 0;
     led_off(4);
   }

} //_CODE_:imgTogButton5:953391:

public void imgTogButton6_click1(GImageToggleButton source, GEvent event) { //_CODE_:imgTogButton6:434487:
  println("imgTogButton6 - GImageToggleButton event occured " + System.currentTimeMillis()%10000000 );

if(sw6 == 0)
   {
     // led 1 on
     sw6 = 1;
     led_on(5);
   }
  else 
   {
     // led 1 off
     sw6 = 0;
     led_off(5);
   }

} //_CODE_:imgTogButton6:434487:

public void imgTogButton7_click1(GImageToggleButton source, GEvent event) { //_CODE_:imgTogButton7:768539:
  println("imgTogButton7 - GImageToggleButton event occured " + System.currentTimeMillis()%10000000 );


if(sw7 == 0)
   {
     // led 1 on
     sw7 = 1;
     led_on(6);
   }
  else 
   {
     // led 1 off
     sw7 = 0;
     led_off(6);
   }
} //_CODE_:imgTogButton7:768539:

public void imgTogButton8_click1(GImageToggleButton source, GEvent event) { //_CODE_:imgTogButton8:739698:
  println("imgTogButton8 - GImageToggleButton event occured " + System.currentTimeMillis()%10000000 );

if(sw8 == 0)
   {
     // led 1 on
     sw8 = 1;
     led_on(7);
   }
  else 
   {
     // led 1 off
     sw8 = 0;
     led_off(7);
   }


} //_CODE_:imgTogButton8:739698:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
imgTogButton1 = new GImageToggleButton(this, 91, 468);
  imgTogButton1.addEventHandler(this, "imgTogButton1_click1");
  imgTogButton2 = new GImageToggleButton(this, 140, 468);
  imgTogButton2.addEventHandler(this, "imgTogButton2_click1");
  imgTogButton3 = new GImageToggleButton(this, 189, 468);
  imgTogButton3.addEventHandler(this, "imgTogButton3_click1");
  imgTogButton4 = new GImageToggleButton(this, 239, 469);
  imgTogButton4.addEventHandler(this, "imgTogButton4_click1");
  imgTogButton5 = new GImageToggleButton(this, 288, 469);
  imgTogButton5.addEventHandler(this, "imgTogButton5_click1");
  imgTogButton6 = new GImageToggleButton(this, 340, 468);
  imgTogButton6.addEventHandler(this, "imgTogButton6_click1");
  imgTogButton7 = new GImageToggleButton(this, 390, 468);
  imgTogButton7.addEventHandler(this, "imgTogButton7_click1");
  imgTogButton8 = new GImageToggleButton(this, 440, 469);
  imgTogButton8.addEventHandler(this, "imgTogButton8_click1");
}

// Variable declarations 
// autogenerated do not edit
GImageToggleButton imgTogButton1; 
GImageToggleButton imgTogButton2; 
GImageToggleButton imgTogButton3; 
GImageToggleButton imgTogButton4; 
GImageToggleButton imgTogButton5; 
GImageToggleButton imgTogButton6; 
GImageToggleButton imgTogButton7; 
GImageToggleButton imgTogButton8; 
